# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(358, 348)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(8, 13, 341, 301))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setIconSize(QtCore.QSize(18, 18))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.accessGrp = QtWidgets.QGroupBox(self.tab1)
        self.accessGrp.setGeometry(QtCore.QRect(10, 10, 311, 131))
        self.accessGrp.setObjectName("accessGrp")
        self.levelCombo = QtWidgets.QComboBox(self.accessGrp)
        self.levelCombo.setGeometry(QtCore.QRect(128, 93, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.levelCombo.setFont(font)
        self.levelCombo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.levelCombo.setEditable(False)
        self.levelCombo.setObjectName("levelCombo")
        self.levelCombo.addItem("")
        self.levelCombo.addItem("")
        self.levelCombo.addItem("")
        self.platformCombo = QtWidgets.QComboBox(self.accessGrp)
        self.platformCombo.setGeometry(QtCore.QRect(128, 61, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.platformCombo.setFont(font)
        self.platformCombo.setObjectName("platformCombo")
        self.accountEdit = QtWidgets.QLineEdit(self.accessGrp)
        self.accountEdit.setGeometry(QtCore.QRect(128, 29, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.accountEdit.setFont(font)
        self.accountEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStatesMinorOutlyingIslands))
        self.accountEdit.setText("")
        self.accountEdit.setObjectName("accountEdit")
        self.accountLabel = QtWidgets.QLabel(self.accessGrp)
        self.accountLabel.setGeometry(QtCore.QRect(10, 29, 101, 19))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.accountLabel.setFont(font)
        self.accountLabel.setTextFormat(QtCore.Qt.AutoText)
        self.accountLabel.setScaledContents(False)
        self.accountLabel.setIndent(10)
        self.accountLabel.setObjectName("accountLabel")
        self.platformLabel = QtWidgets.QLabel(self.accessGrp)
        self.platformLabel.setGeometry(QtCore.QRect(10, 61, 101, 19))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.platformLabel.setFont(font)
        self.platformLabel.setTextFormat(QtCore.Qt.AutoText)
        self.platformLabel.setScaledContents(False)
        self.platformLabel.setIndent(10)
        self.platformLabel.setObjectName("platformLabel")
        self.levelLabel = QtWidgets.QLabel(self.accessGrp)
        self.levelLabel.setGeometry(QtCore.QRect(10, 93, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.levelLabel.setFont(font)
        self.levelLabel.setTextFormat(QtCore.Qt.AutoText)
        self.levelLabel.setScaledContents(False)
        self.levelLabel.setIndent(10)
        self.levelLabel.setObjectName("levelLabel")
        self.otherGroup = QtWidgets.QGroupBox(self.tab1)
        self.otherGroup.setGeometry(QtCore.QRect(10, 190, 311, 71))
        self.otherGroup.setObjectName("otherGroup")
        self.showGitBox = QtWidgets.QCheckBox(self.otherGroup)
        self.showGitBox.setGeometry(QtCore.QRect(40, 30, 91, 21))
        self.showGitBox.setObjectName("showGitBox")
        self.shoLogBox = QtWidgets.QCheckBox(self.otherGroup)
        self.shoLogBox.setGeometry(QtCore.QRect(160, 30, 101, 20))
        self.shoLogBox.setObjectName("shoLogBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab1)
        self.layoutWidget_2.setGeometry(QtCore.QRect(23, 150, 291, 29))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clearBtn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.clearBtn.setObjectName("clearBtn")
        self.horizontalLayout.addWidget(self.clearBtn)
        self.confirmBtn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.confirmBtn.setObjectName("confirmBtn")
        self.horizontalLayout.addWidget(self.confirmBtn)
        self.setTokenBtn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.setTokenBtn.setObjectName("setTokenBtn")
        self.horizontalLayout.addWidget(self.setTokenBtn)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.importRepoGrp = QtWidgets.QGroupBox(self.tab2)
        self.importRepoGrp.setGeometry(QtCore.QRect(10, 10, 311, 101))
        self.importRepoGrp.setObjectName("importRepoGrp")
        self.platformEdit = QtWidgets.QLineEdit(self.importRepoGrp)
        self.platformEdit.setGeometry(QtCore.QRect(130, 30, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.platformEdit.setFont(font)
        self.platformEdit.setText("")
        self.platformEdit.setObjectName("platformEdit")
        self.platformNameLabel = QtWidgets.QLabel(self.importRepoGrp)
        self.platformNameLabel.setGeometry(QtCore.QRect(18, 29, 81, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.platformNameLabel.setFont(font)
        self.platformNameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.platformNameLabel.setScaledContents(False)
        self.platformNameLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.platformNameLabel.setWordWrap(True)
        self.platformNameLabel.setIndent(10)
        self.platformNameLabel.setObjectName("platformNameLabel")
        self.fileButton = QtWidgets.QPushButton(self.importRepoGrp)
        self.fileButton.setGeometry(QtCore.QRect(130, 62, 161, 27))
        self.fileButton.setObjectName("fileButton")
        self.chooseFileLabel = QtWidgets.QLabel(self.importRepoGrp)
        self.chooseFileLabel.setGeometry(QtCore.QRect(18, 61, 81, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.chooseFileLabel.setFont(font)
        self.chooseFileLabel.setTextFormat(QtCore.Qt.AutoText)
        self.chooseFileLabel.setScaledContents(False)
        self.chooseFileLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.chooseFileLabel.setIndent(10)
        self.chooseFileLabel.setObjectName("chooseFileLabel")
        self.clearBtn2 = QtWidgets.QPushButton(self.tab2)
        self.clearBtn2.setGeometry(QtCore.QRect(23, 230, 92, 27))
        self.clearBtn2.setObjectName("clearBtn2")
        self.importRepoBtn = QtWidgets.QPushButton(self.tab2)
        self.importRepoBtn.setGeometry(QtCore.QRect(121, 230, 93, 27))
        self.importRepoBtn.setObjectName("importRepoBtn")
        self.importGitBtn = QtWidgets.QPushButton(self.tab2)
        self.importGitBtn.setGeometry(QtCore.QRect(220, 230, 92, 27))
        self.importGitBtn.setObjectName("importGitBtn")
        self.importGitGrp = QtWidgets.QGroupBox(self.tab2)
        self.importGitGrp.setGeometry(QtCore.QRect(10, 120, 311, 101))
        self.importGitGrp.setObjectName("importGitGrp")
        self.gitNameEdit = QtWidgets.QLineEdit(self.importGitGrp)
        self.gitNameEdit.setGeometry(QtCore.QRect(130, 30, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gitNameEdit.setFont(font)
        self.gitNameEdit.setText("")
        self.gitNameEdit.setObjectName("gitNameEdit")
        self.gitNameLabel = QtWidgets.QLabel(self.importGitGrp)
        self.gitNameLabel.setGeometry(QtCore.QRect(18, 29, 81, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.gitNameLabel.setFont(font)
        self.gitNameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.gitNameLabel.setScaledContents(False)
        self.gitNameLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.gitNameLabel.setWordWrap(True)
        self.gitNameLabel.setIndent(10)
        self.gitNameLabel.setObjectName("gitNameLabel")
        self.gitLinkLabel = QtWidgets.QLabel(self.importGitGrp)
        self.gitLinkLabel.setGeometry(QtCore.QRect(18, 61, 81, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.gitLinkLabel.setFont(font)
        self.gitLinkLabel.setTextFormat(QtCore.Qt.AutoText)
        self.gitLinkLabel.setScaledContents(False)
        self.gitLinkLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.gitLinkLabel.setIndent(10)
        self.gitLinkLabel.setObjectName("gitLinkLabel")
        self.gitLinkEdit = QtWidgets.QLineEdit(self.importGitGrp)
        self.gitLinkEdit.setGeometry(QtCore.QRect(130, 60, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gitLinkEdit.setFont(font)
        self.gitLinkEdit.setText("")
        self.gitLinkEdit.setObjectName("gitLinkEdit")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.importMemberGrp = QtWidgets.QGroupBox(self.tab3)
        self.importMemberGrp.setGeometry(QtCore.QRect(10, 10, 311, 131))
        self.importMemberGrp.setObjectName("importMemberGrp")
        self.platformLabel_2 = QtWidgets.QLabel(self.importMemberGrp)
        self.platformLabel_2.setGeometry(QtCore.QRect(18, 29, 81, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.platformLabel_2.setFont(font)
        self.platformLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.platformLabel_2.setScaledContents(False)
        self.platformLabel_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.platformLabel_2.setWordWrap(True)
        self.platformLabel_2.setIndent(10)
        self.platformLabel_2.setObjectName("platformLabel_2")
        self.fileButton_2 = QtWidgets.QPushButton(self.importMemberGrp)
        self.fileButton_2.setGeometry(QtCore.QRect(130, 90, 161, 27))
        self.fileButton_2.setObjectName("fileButton_2")
        self.chooseFileLabel_2 = QtWidgets.QLabel(self.importMemberGrp)
        self.chooseFileLabel_2.setGeometry(QtCore.QRect(18, 89, 81, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.chooseFileLabel_2.setFont(font)
        self.chooseFileLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.chooseFileLabel_2.setScaledContents(False)
        self.chooseFileLabel_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.chooseFileLabel_2.setIndent(10)
        self.chooseFileLabel_2.setObjectName("chooseFileLabel_2")
        self.platformCombo_2 = QtWidgets.QComboBox(self.importMemberGrp)
        self.platformCombo_2.setGeometry(QtCore.QRect(130, 30, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.platformCombo_2.setFont(font)
        self.platformCombo_2.setObjectName("platformCombo_2")
        self.levelLabel_2 = QtWidgets.QLabel(self.importMemberGrp)
        self.levelLabel_2.setGeometry(QtCore.QRect(18, 59, 81, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.levelLabel_2.setFont(font)
        self.levelLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.levelLabel_2.setScaledContents(False)
        self.levelLabel_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.levelLabel_2.setWordWrap(True)
        self.levelLabel_2.setIndent(10)
        self.levelLabel_2.setObjectName("levelLabel_2")
        self.levelCombo_2 = QtWidgets.QComboBox(self.importMemberGrp)
        self.levelCombo_2.setGeometry(QtCore.QRect(130, 60, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.levelCombo_2.setFont(font)
        self.levelCombo_2.setObjectName("levelCombo_2")
        self.levelCombo_2.addItem("")
        self.levelCombo_2.addItem("")
        self.levelCombo_2.addItem("")
        self.showLogBtn_2 = QtWidgets.QPushButton(self.tab3)
        self.showLogBtn_2.setGeometry(QtCore.QRect(50, 150, 92, 27))
        self.showLogBtn_2.setObjectName("showLogBtn_2")
        self.importMemberBtn = QtWidgets.QPushButton(self.tab3)
        self.importMemberBtn.setGeometry(QtCore.QRect(190, 150, 93, 27))
        self.importMemberBtn.setObjectName("importMemberBtn")
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.closeSubwinBtn = QtWidgets.QPushButton(self.tab4)
        self.closeSubwinBtn.setGeometry(QtCore.QRect(190, 120, 92, 27))
        self.closeSubwinBtn.setObjectName("closeSubwinBtn")
        self.showTableBtn = QtWidgets.QPushButton(self.tab4)
        self.showTableBtn.setGeometry(QtCore.QRect(50, 120, 93, 27))
        self.showTableBtn.setObjectName("showTableBtn")
        self.importMemberGrp_2 = QtWidgets.QGroupBox(self.tab4)
        self.importMemberGrp_2.setGeometry(QtCore.QRect(10, 10, 311, 101))
        self.importMemberGrp_2.setObjectName("importMemberGrp_2")
        self.platformLabel_3 = QtWidgets.QLabel(self.importMemberGrp_2)
        self.platformLabel_3.setGeometry(QtCore.QRect(18, 29, 81, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.platformLabel_3.setFont(font)
        self.platformLabel_3.setTextFormat(QtCore.Qt.AutoText)
        self.platformLabel_3.setScaledContents(False)
        self.platformLabel_3.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.platformLabel_3.setWordWrap(True)
        self.platformLabel_3.setIndent(10)
        self.platformLabel_3.setObjectName("platformLabel_3")
        self.platformCombo_3 = QtWidgets.QComboBox(self.importMemberGrp_2)
        self.platformCombo_3.setGeometry(QtCore.QRect(130, 30, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.platformCombo_3.setFont(font)
        self.platformCombo_3.setObjectName("platformCombo_3")
        self.gitLabel = QtWidgets.QLabel(self.importMemberGrp_2)
        self.gitLabel.setGeometry(QtCore.QRect(18, 59, 81, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.gitLabel.setFont(font)
        self.gitLabel.setTextFormat(QtCore.Qt.AutoText)
        self.gitLabel.setScaledContents(False)
        self.gitLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.gitLabel.setWordWrap(True)
        self.gitLabel.setIndent(10)
        self.gitLabel.setObjectName("gitLabel")
        self.gitCombo = QtWidgets.QComboBox(self.importMemberGrp_2)
        self.gitCombo.setGeometry(QtCore.QRect(130, 60, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gitCombo.setFont(font)
        self.gitCombo.setObjectName("gitCombo")
        self.tabWidget.addTab(self.tab4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 358, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.platformNameLabel.setBuddy(self.accountEdit)
        self.chooseFileLabel.setBuddy(self.accountEdit)
        self.gitNameLabel.setBuddy(self.accountEdit)
        self.gitLinkLabel.setBuddy(self.accountEdit)
        self.platformLabel_2.setBuddy(self.accountEdit)
        self.chooseFileLabel_2.setBuddy(self.accountEdit)
        self.levelLabel_2.setBuddy(self.accountEdit)
        self.platformLabel_3.setBuddy(self.accountEdit)
        self.gitLabel.setBuddy(self.accountEdit)
        self.confirmBtn.setDisabled(True)
        self.importRepoBtn.setDisabled(True)
        self.importGitBtn.setDisabled(True)
        

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.clearBtn.clicked.connect(self.accountEdit.clear)
        self.clearBtn2.clicked.connect(self.platformEdit.clear)
        self.clearBtn2.clicked.connect(self.gitNameEdit.clear)
        self.clearBtn2.clicked.connect(self.gitLinkEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.accountEdit)
        MainWindow.setTabOrder(self.accountEdit, self.platformCombo)
        MainWindow.setTabOrder(self.platformCombo, self.levelCombo)
        MainWindow.setTabOrder(self.levelCombo, self.confirmBtn)
        MainWindow.setTabOrder(self.confirmBtn, self.clearBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gitlab Access 2.0"))
        self.accessGrp.setTitle(_translate("MainWindow", "Access Setting"))
        self.levelCombo.setItemText(0, _translate("MainWindow", "reporter"))
        self.levelCombo.setItemText(1, _translate("MainWindow", "developer"))
        self.levelCombo.setItemText(2, _translate("MainWindow", "maintainer"))
        self.accountLabel.setText(_translate("MainWindow", "域账号"))
        self.platformLabel.setText(_translate("MainWindow", "平台"))
        self.levelLabel.setText(_translate("MainWindow", "权限级别"))
        self.otherGroup.setTitle(_translate("MainWindow", "Other"))
        self.showGitBox.setText(_translate("MainWindow", "显示仓库"))
        self.shoLogBox.setText(_translate("MainWindow", "显示log"))
        self.clearBtn.setText(_translate("MainWindow", "清空输入"))
        self.confirmBtn.setText(_translate("MainWindow", "确认开通"))
        self.setTokenBtn.setText(_translate("MainWindow", "导入Token"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "权限开通"))
        self.importRepoGrp.setTitle(_translate("MainWindow", "Import Platform"))
        self.platformNameLabel.setText(_translate("MainWindow", "平台名称"))
        self.fileButton.setText(_translate("MainWindow", "选择xml文件"))
        self.chooseFileLabel.setText(_translate("MainWindow", "选择文件"))
        self.clearBtn2.setText(_translate("MainWindow", "清空输入"))
        self.importRepoBtn.setText(_translate("MainWindow", "导入平台"))
        self.importGitBtn.setText(_translate("MainWindow", "导入仓库"))
        self.importGitGrp.setTitle(_translate("MainWindow", "Import Repository"))
        self.gitNameLabel.setText(_translate("MainWindow", "仓库名称"))
        self.gitLinkLabel.setText(_translate("MainWindow", "仓库ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "导入平台"))
        self.importMemberGrp.setTitle(_translate("MainWindow", "Import Members"))
        self.platformLabel_2.setText(_translate("MainWindow", "选择平台"))
        self.fileButton_2.setText(_translate("MainWindow", "选择成员名单"))
        self.chooseFileLabel_2.setText(_translate("MainWindow", "选择文件"))
        self.levelLabel_2.setText(_translate("MainWindow", "选择权限"))
        self.levelCombo_2.setItemText(0, _translate("MainWindow", "reporter"))
        self.levelCombo_2.setItemText(1, _translate("MainWindow", "developer"))
        self.levelCombo_2.setItemText(2, _translate("MainWindow", "maintainer"))
        self.showLogBtn_2.setText(_translate("MainWindow", "显示log"))
        self.importMemberBtn.setText(_translate("MainWindow", "导入成员"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "批量导入成员"))
        self.closeSubwinBtn.setText(_translate("MainWindow", "关闭子窗口"))
        self.showTableBtn.setText(_translate("MainWindow", "查看权限"))
        self.importMemberGrp_2.setTitle(_translate("MainWindow", "View Permissions"))
        self.platformLabel_3.setText(_translate("MainWindow", "选择平台"))
        self.gitLabel.setText(_translate("MainWindow", "选择仓库"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("MainWindow", "查看权限"))
